version: "2"
services:
    db:
        image: postgres:9.5.2
        volumes:
            - /opt/starter/psql:/var/lib/postgresql/data/pgdata
        env_file:
            - ./.docker/config/environment/development.env

    redis:
        restart: always
        image: redis:latest
        ports:
          - "6379:6379"

    webserver:
        build:
            context: .
            dockerfile: ./.docker/services/webserver/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - webapp
        volumes_from:
            - webapp
        env_file:
            - ./.docker/config/environment/development.env

    webapp:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./starter:/srv/starter
            - /srv/static-files
        expose:
            - "8000"
        depends_on:
            - db
            - redis
        env_file:
            - ./.docker/config/environment/development.env
